### ISSUE TITLE
web3 1.0 usability (this.provider.sendAsync is not a function)

### ISSUE THREAD

**Issue by alex-miller-0** [zmitton/eth-proof#2]
I'm trying to build a proof using a web3 1.0 provider:

```
const epA = new EthProof(providerA);
const _providerB = `http://${truffleConf.developmentB.host}:${truffleConf.developmentB.port}`;
const providerB = new Web3.providers.HttpProvider(_providerB);

...

epB.getTransactionProof(depositBlock.transactions[0])
.then((proof) => {
   console.log('proof', proof);
})
```

Which gives me the following error:

```
TypeError: this.provider.sendAsync is not a function
    at RequestManager.sendAsync (/Users/alexmiller/Projects/trustless-relay/node_modules/eth-proof/node_modules/web3/lib/web3/requestmanager.js:80:19)
    at Eth.send [as getTransaction] (/Users/alexmiller/Projects/trustless-relay/node_modules/eth-proof/node_modules/web3/lib/web3/method.js:141:42)
    at Promise (/Users/alexmiller/Projects/trustless-relay/node_modules/eth-proof/buildProof.js:152:21)
    at Promise (<anonymous>)
    at BuildProof.getTransactionProof (/Users/alexmiller/Projects/trustless-relay/node_modules/eth-proof/buildProof.js:149:10)
    at Context.it (/Users/alexmiller/Projects/trustless-relay/test/relay.js:203:11)
    at callFnAsync (/usr/local/lib/node_modules/truffle/node_modules/mocha/lib/runnable.js:371:21)
    at Test.Runnable.run (/usr/local/lib/node_modules/truffle/node_modules/mocha/lib/runnable.js:318:7)
    at Runner.runTest (/usr/local/lib/node_modules/truffle/node_modules/mocha/lib/runner.js:443:10)
    at /usr/local/lib/node_modules/truffle/node_modules/mocha/lib/runner.js:549:12
    at next (/usr/local/lib/node_modules/truffle/node_modules/mocha/lib/runner.js:361:14)
    at /usr/local/lib/node_modules/truffle/node_modules/mocha/lib/runner.js:371:7
    at next (/usr/local/lib/node_modules/truffle/node_modules/mocha/lib/runner.js:295:14)
    at Immediate.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

I'm trying to figure out why this would be, but I think it's because I'm using web3 1.0. I'll try to dig into this more, but putting in this issue in case there's an incompatibility issue here.

**Comment by NaceurBouhamed** [comment]
I know this is old, but in case someone didn't find a fix
just add this before creating the instance :
Web3.providers.HttpProvider.prototype.sendAsync = Web3.providers.HttpProvider.prototype.send;

**Comment by zmitton** [comment]
hey guys, is there something I should fix on my end? seems like just an issue with the way you were setting up your provider?

**Comment by TankRyze** [comment]
> hey guys, is there something I should fix on my end? seems like just an issue with the way you were setting up your provider?
How to set up a proper web3 object provider?
